Create a stack from of subtypes maps from all task and trial

In [1]:
import seaborn as sns
import os
import numpy as np
from scipy import stats, integrate
import scipy.io as sio
import pandas as pd
from pandas.tools.plotting import scatter_matrix
import seaborn as sns; sns.set(color_codes=True)
import matplotlib.pyplot as plt

In [2]:
# load good stuff
%matplotlib inline
%load_ext rpy2.ipython
%load_ext oct2py.ipython
sns.set(color_codes=True)

In [3]:
import warnings
warnings.filterwarnings('ignore')

In [37]:
#  Set path
path_root = '/home/yassinebha/Drive/HCP/subtypes_scores/26-10-2016/'
list_subtype_folder = ['subtype_5_spm_EMOTION_23-May-2017','subtype_5_spm_GAMBLING_19-Jun-2017','subtype_5_spm_LANGUAGE_18-Jun-2017',
                      'subtype_5_spm_MOTOR_19-Jun-2017','subtype_5_spm_RELATIONAL_18-Jun-2017','subtype_5_spm_SOCIAL_18-Jun-2017',
                       'subtype_5_spm_WM_18-Jun-2017']
list_subtype = ['sub1','sub2','sub3','sub4','sub5']

In [40]:
for cx,folder in enumerate(list_subtype_folder):
    path_network =  os.path.join(path_root,folder,'networks/')
    list_trial  = [f for f in os.listdir(path_network)]
    for ix,trial_name in enumerate(list_trial) :
        mat_file = os.path.join(path_network,trial_name,'subtype_{}.mat'.format(trial_name))
        %octave_push mat_file
        %octave mat_load = load(mat_file);
        %octave_pull mat_load
        subtype = mat_load.sub.map.T
        subtype_name = ['{}_{}'.format(subt,trial_name) for subt in list_subtype ]
        if ix == 0 and cx == 0:
            subtype_final = subtype
            subtype_name_final = subtype_name
        else:
            subtype_final = [np.concatenate([subtype_final[x], subtype[x]]) for x in range(np.shape(subtype)[0])]
            subtype_name_final = np.concatenate([subtype_name_final, subtype_name]) 

In [41]:
# make dataframe 
all_stack_df = pd.DataFrame(subtype_final,columns=subtype_name_final)
all_stack_df.head()

sub1_fear  sub2_fear     sub3_fear     sub4_fear  sub5_fear  \
0  -0.000026  -0.000010  3.400174e-06  1.969976e-05   0.000001   
1  -0.000030  -0.000050  7.557251e-05  1.935898e-05  -0.000020   
2  -0.000037  -0.000062  2.097875e-04 -5.504649e-05  -0.000034   
3   0.000001   0.000018 -1.056633e-05  2.286825e-06  -0.000005   
4  -0.000007   0.000009  5.834449e-07  7.194440e-07  -0.000002   

   sub1_contrast_loss_event_vs_neut_event  \
0                           -2.722667e-04   
1                           -2.416968e-05   
2                            7.750296e-05   
3                           -8.490994e-06   
4                            8.046937e-07   

   sub2_contrast_loss_event_vs_neut_event  \
0                                0.000034   
1                               -0.000024   
2                                0.000105   
3                                0.000001   
4                                0.000002   

   sub3_contrast_loss_event_vs_neut_event  \
0                            3.307610e-05   
1                           -9.189761e-05   
2                           -1.515700e-04   
3                            6.710994e-06   
4                            5.579041e-07   

   sub4_contrast_loss_event_vs_neut_event  \
0                                0.000092   
1                                0.000128   
2                                0.000077   
3                                0.000010   
4                               -0.000009   

   sub5_contrast_loss_event_vs_neut_event      ...        sub1_places  \
0                               -0.000035      ...       7.089784e-05   
1                               -0.000043      ...       5.864750e-05   
2                               -0.000081      ...       3.866714e-05   
3                               -0.000013      ...      -2.469192e-07   
4                                0.000007      ...       9.066289e-07   

   sub2_places   sub3_places  sub4_places  sub5_places  sub1_2bk  sub2_2bk  \
0     0.000071  2.997301e-06    -0.000042    -0.000037  0.000049 -0.000026   
1    -0.000017  3.228650e-05    -0.000051    -0.000006  0.000039 -0.000018   
2     0.000037 -2.390819e-06     0.000006    -0.000032 -0.000008 -0.000013   
3     0.000003 -6.788072e-07    -0.000007     0.000003  0.000010 -0.000011   
4     0.000009 -9.413969e-07    -0.000012     0.000003  0.000006 -0.000010   

   sub3_2bk  sub4_2bk      sub5_2bk  
0  0.000066 -0.000129  3.228139e-06  
1  0.000081 -0.000160  8.092133e-06  
2  0.000030 -0.000075  3.030099e-05  
3 -0.000003  0.000002  2.005255e-06  
4 -0.000004  0.000011  4.487713e-07  

[5 rows x 170 columns]

In [44]:
# save final stack
all_stack_df.to_csv(os.path.join(path_root,'pheno/all_subtype_stack.csv'))

SyntaxError: unexpected EOF while parsing (<ipython-input-44-4d170c42148f>, line 2)

In [66]:
concat

[array([  4.88365492e-05,  -2.64728731e-05,   6.57775362e-05,
         -1.29002089e-04,   3.22813901e-06,   4.88365492e-05,
         -2.64728731e-05,   6.57775362e-05,  -1.29002089e-04,
          3.22813901e-06]),
 array([  3.90995816e-05,  -1.80422509e-05,   8.14553629e-05,
         -1.59882917e-04,   8.09213348e-06,   3.90995816e-05,
         -1.80422509e-05,   8.14553629e-05,  -1.59882917e-04,
          8.09213348e-06]),
 array([ -7.63293411e-06,  -1.29691474e-05,   2.99652757e-05,
         -7.53612566e-05,   3.03009872e-05,  -7.63293411e-06,
         -1.29691474e-05,   2.99652757e-05,  -7.53612566e-05,
          3.03009872e-05]),
 array([  1.02031424e-05,  -1.11790126e-05,  -3.23773379e-06,
          2.48352402e-06,   2.00525523e-06,   1.02031424e-05,
         -1.11790126e-05,  -3.23773379e-06,   2.48352402e-06,
          2.00525523e-06]),
 array([  6.08855810e-06,  -1.02432817e-05,  -3.78160391e-06,
          1.08669014e-05,   4.48771295e-07,   6.08855810e-06,
         -1.02432817

In [51]:
subtype = mat_load.sub.map.T

In [55]:
subtype_final = pd.Series(subtype.tolist())

In [56]:
subtype_final = pd.concat([subtype_final,pd.Series(subtype.tolist())],axis=1)

In [57]:
subtype_final


0  \
0      [4.883654915132813e-05, -2.6472873066365345e-0...   
1      [3.9099581559960073e-05, -1.8042250926495732e-...   
2      [-7.632934105266027e-06, -1.2969147438760874e-...   
3      [1.020314240898355e-05, -1.1179012587456306e-0...   
4      [6.0885580955189235e-06, -1.0243281666069907e-...   
5      [4.082985074261422e-06, -1.7618931805895015e-0...   
6      [-4.541972248470208e-06, -3.619544636420951e-0...   
7      [6.901178598375971e-06, -1.9943596929591662e-0...   
8      [1.036802391456727e-05, -2.7963239770490917e-0...   
9      [2.191522746235659e-05, -2.4903947850122428e-0...   
10     [0.00011080518341396989, -6.276951571375986e-0...   
11     [8.255934767218967e-05, -1.2066402351273107e-0...   
12     [3.3425884042781375e-06, 3.1072495917032594e-0...   
13     [5.808174618482833e-06, 7.346653312032983e-06,...   
14     [-5.735784974887999e-06, -5.891936410853692e-0...   
15     [5.432583025735659e-06, -2.42336514029509e-05,...   
16     [-2.4595595468252263e-07, -3.391743571748825e-...   
17     [-3.142135851905822e-06, -4.54075671705454e-06...   
18     [6.624106431793802e-06, -5.743438221642478e-08...   
19     [4.795393156838093e-05, -5.399410470998663e-05...   
20     [6.353790317216517e-05, -4.3739699185173066e-0...   
21     [0.00016086369704903353, -2.4158849676471154e-...   
22     [0.0001641751087982486, -4.338839116516266e-05...   
23     [0.00018059978380082907, -4.880584560115933e-0...   
24     [9.890850057059918e-05, 1.1382115035775756e-05...   
25     [2.0328110709378936e-05, 3.0249239032906737e-0...   
26     [4.156867174918109e-06, -2.5882785156063027e-0...   
27     [1.7607699133730947e-06, -5.660364369212409e-0...   
28     [1.7669797479952045e-06, -4.5590188732786044e-...   
29     [9.50662722941545e-06, -9.980020590186432e-06,...   
...                                                  ...   
59870  [0.0003912268228164373, 3.4755335966415876e-05...   
59871  [0.0002986185170279662, -0.0001226874640584686...   
59872  [0.00024157380465165761, -4.056737030407989e-0...   
59873  [0.00023207682164295743, -9.449598218033756e-0...   
59874  [0.00020610483584292705, -0.000201814491770362...   
59875  [0.000253724293981169, -0.0001768161717852953,...   
59876  [0.0002553704499692293, -0.0001294654368811322...   
59877  [0.00029302204464534166, -5.7277510345686495e-...   
59878  [0.00015653915409348984, 3.425111410531916e-06...   
59879  [0.00017791373035960396, -3.348486595616412e-0...   
59880  [0.00020438479494018413, -9.142800596736253e-0...   
59881  [0.00020684445532059525, -0.000182466650028351...   
59882  [0.0002950539625821986, -0.0001948404250468022...   
59883  [0.0002654830276120119, -0.0001240582214645856...   
59884  [0.0002647115024441093, -8.594630977494499e-05...   
59885  [0.0003419063814978576, -4.767448340038849e-05...   
59886  [0.00013446725525367425, 1.6767087500063856e-0...   
59887  [0.00017936906346923952, -8.393159889977312e-0...   
59888  [0.00020832573847265836, -6.44592647274132e-05...   
59889  [0.00021448802715587166, -0.000151971389655474...   
59890  [0.0003423787588708226, -0.0001567973529586507...   
59891  [0.00032578688049463716, -0.000121906058329920...   
59892  [0.00032809355426331103, -0.000114155482283226...   
59893  [0.00038561100387511296, -7.168053902431306e-0...   
59894  [0.00037319736900218506, -0.000104852496667113...   
59895  [0.00021799025758718966, -3.7936647649820306e-...   
59896  [0.0002806565373297048, 1.826291994453249e-05,...   
59897  [0.0002123466164743664, 2.6077001339809185e-05...   
59898  [0.00027426601169366454, -3.9222759273544684e-...   
59899  [0.0002454174226811085, 4.313819848613888e-06,...   

                                                       1  
0      [4.883654915132813e-05, -2.6472873066365345e-0...  
1      [3.9099581559960073e-05, -1.8042250926495732e-...  
2      [-7.632934105266027e-06, -1.2969147438760874e-...  
3      [1.020314240898355e-05, -1.1179012587456306e-0...  
4      [6.0885580955189235e-06, -1.0243